"""auto

Revision ID: 1731ebaed6e5
Revises: c9dd42d3d194
Create Date: 2025-09-23 05:29:08.194699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1731ebaed6e5'
down_revision: Union[str, Sequence[str], None] = 'c9dd42d3d194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_column('order_items', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('order_items', 'total_price')
    # ### end Alembic commands ###
